// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: filterer.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FiltererClient is the client API for Filterer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiltererClient interface {
	AddInterestTopic(ctx context.Context, in *AddInterestTopicRequest, opts ...grpc.CallOption) (*AddInterestTopicReply, error)
}

type filtererClient struct {
	cc grpc.ClientConnInterface
}

func NewFiltererClient(cc grpc.ClientConnInterface) FiltererClient {
	return &filtererClient{cc}
}

func (c *filtererClient) AddInterestTopic(ctx context.Context, in *AddInterestTopicRequest, opts ...grpc.CallOption) (*AddInterestTopicReply, error) {
	out := new(AddInterestTopicReply)
	err := c.cc.Invoke(ctx, "/grpc_api.Filterer/AddInterestTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiltererServer is the server API for Filterer service.
// All implementations must embed UnimplementedFiltererServer
// for forward compatibility
type FiltererServer interface {
	AddInterestTopic(context.Context, *AddInterestTopicRequest) (*AddInterestTopicReply, error)
	mustEmbedUnimplementedFiltererServer()
}

// UnimplementedFiltererServer must be embedded to have forward compatible implementations.
type UnimplementedFiltererServer struct {
}

func (UnimplementedFiltererServer) AddInterestTopic(context.Context, *AddInterestTopicRequest) (*AddInterestTopicReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInterestTopic not implemented")
}
func (UnimplementedFiltererServer) mustEmbedUnimplementedFiltererServer() {}

// UnsafeFiltererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiltererServer will
// result in compilation errors.
type UnsafeFiltererServer interface {
	mustEmbedUnimplementedFiltererServer()
}

func RegisterFiltererServer(s grpc.ServiceRegistrar, srv FiltererServer) {
	s.RegisterService(&Filterer_ServiceDesc, srv)
}

func _Filterer_AddInterestTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInterestTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiltererServer).AddInterestTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Filterer/AddInterestTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiltererServer).AddInterestTopic(ctx, req.(*AddInterestTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Filterer_ServiceDesc is the grpc.ServiceDesc for Filterer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Filterer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Filterer",
	HandlerType: (*FiltererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddInterestTopic",
			Handler:    _Filterer_AddInterestTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filterer.proto",
}
